services:
  - type: web
    name: raksha-investor
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt && cd frontend && npm install && npm run build && cd .."
    startCommand: "python run.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: NODE_VERSION
        value: 20.12.0
      - key: ENV
        value: production
